# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ChooseMyDestination
                                 A QGIS plugin
 根据自定义指标及权重选择目的地
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-09
        copyright            : (C) 2025 by MaritimeDay
        email                : Connor_RK800@163.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ChooseMyDestination class from file ChooseMyDestination.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .choose_my_destination import ChooseMyDestination
    return ChooseMyDestination(iface)
